### ISSUE TITLE
About APPID

### ISSUE THREAD

**Issue by coolkit-carl** [basvankuijck/homeassistant-config#18]
Hello,

I'm the technical staff of CoolKit eWeLink, how did you get our APPID and APP Secret?

**Comment by basvankuijck** [comment]
Hi @coolkit-carl,

what do you mean by "get our APPID and APP Secret"?
Do I have any references to it in my code?

**Comment by coolkit-carl** [comment]
Yes, it’s in https://github.com/basvankuijck/homeassistant-config/blob/master/custom_components/sonoff/sonoff_cloud.py

**Comment by basvankuijck** [comment]
Ah okay, that's a script (custom component) made by someone else: https://github.com/AlexxIT/SonoffLAN
I wouldn't know he/she obtained it.
But if I had to guess, probably by just sniffing network requests from the eWeLink app

**Comment by coolkit-carl** [comment]
> Ah okay, that's a script (custom component) made by someone else: https://github.com/AlexxIT/SonoffLAN
> I wouldn't know he/she obtained it.
> But if I had to guess, probably by just sniffing network requests from the eWeLink app

Okay, I will communicate with him.
